### ISSUE TITLE
Signaturepad Xamarin and Android

### ISSUE THREAD

**Issue by jordixip** [xamarin/SignaturePad#124] opened 2018-03-19 01:32 UTC
Hello,

I developed a small Android application with save and clear features, and it is working fine. Save button save directly in a ftp server, and clear button, clears all the image.

I wish to know how to clear only a zone, like an eraser. So changing the arrow cursor, to an eraser, and clear only the zone affected.

On the other hand, I doesn't know how to use another kind of controls, so... not using buttons, and use something more small.

I used xaml to the view, and c# for the code, mainly the events for onsave, onclear.

If needed code, I'll add.

Thank you

**Comment by mattleibow** [comment] 2018-05-15 20:44
This is a duplicate of https://github.com/xamarin/SignaturePad/issues/125.

As noted there, this is not really supported and probably won't be in the near future as this is not what this control is designed to do.

**Closed by mattleibow** 2018-05-15 20:44 UTC
Labels: duplicate
