### ISSUE TITLE
Message: [ObjectDisposedException: Cannot access a disposed object. Object name: 'Android.Graphics.RectF'.]

### ISSUE THREAD

**Issue by lbulegato** [xamarin/SignaturePad#52] opened 2017-01-26 10:42 UTC
Thanks to Raygun (crashlog system) we are receiving a lot of this kind of error from our android app.
Here the stacktrace

```
Java.Interop.JniPeerMembers.AssertSelf(Java.Interop.IJavaPeerable self) in <b72830eae84a465dba3c71c416533d20>:0
 Java.Interop.JniPeerMembers+JniInstanceFields.SetValue(System.String encodedMember, Java.Interop.IJavaPeerable self, System.Single value) in <b72830eae84a465dba3c71c416533d20>:0
 Android.Graphics.RectF.set_Left(System.Single value) in <fc5b043c2b92453a93388ea815daa6f7>:0
 SignaturePad.SignaturePadView.resetBounds(System.Single touchX, System.Single touchY) in <2906e1341ea84a8aa79237e119342274>:0
 SignaturePad.SignaturePadView.handleTouch(Android.Views.MotionEvent e) in <2906e1341ea84a8aa79237e119342274>:0
 SignaturePad.SignaturePadView.OnTouchEvent(Android.Views.MotionEvent e) in <2906e1341ea84a8aa79237e119342274>:0
 Android.Views.View.n_OnTouchEvent_Landroid_view_MotionEvent_(System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_e) in <fc5b043c2b92453a93388ea815daa6f7>:0
    (wrapper dynamic-method) System.Object:5c542839-2704-40dc-83c7-07a5daea3fb2 (intptr,intptr,intptr)
```

Unfortunately we are not able to replicate the error on debug.
This kind of error started after the last update to Google libraries 

```
<package id="Xamarin.Android.Support.Animated.Vector.Drawable"
version="24.2.1" targetFramework="monoandroid70" />
<package id="Xamarin.Android.Support.Compat" version="24.2.1"
targetFramework="monoandroid70" />
<package id="Xamarin.Android.Support.Core.UI" version="24.2.1"
targetFramework="monoandroid70" />
<package id="Xamarin.Android.Support.Core.Utils" version="24.2.1"
targetFramework="monoandroid70" />
<package id="Xamarin.Android.Support.Design" version="24.2.1"
targetFramework="monoandroid70" />
<package id="Xamarin.Android.Support.Fragment" version="24.2.1"
targetFramework="monoandroid70" />
<package id="Xamarin.Android.Support.Media.Compat" version="24.2.1"
targetFramework="monoandroid70" />
<package id="Xamarin.Android.Support.v4" version="24.2.1"
targetFramework="monoandroid70" />
<package id="Xamarin.Android.Support.v7.AppCompat" version="24.2.1"
targetFramework="monoandroid70" />
<package id="Xamarin.Android.Support.v7.RecyclerView" version="24.2.1"
targetFramework="monoandroid70" />
<package id="Xamarin.Android.Support.Vector.Drawable" version="24.2.1"
targetFramework="monoandroid70" /> 
```

**Comment by lbulegato** [comment] 2017-01-26 10:44
Here the google libraries we are using

<package id="Xamarin.Android.Support.Animated.Vector.Drawable"
version="24.2.1" targetFramework="monoandroid70" />
<package id="Xamarin.Android.Support.Compat" version="24.2.1"
targetFramework="monoandroid70" />
<package id="Xamarin.Android.Support.Core.UI" version="24.2.1"
targetFramework="monoandroid70" />
<package id="Xamarin.Android.Support.Core.Utils" version="24.2.1"
targetFramework="monoandroid70" />
<package id="Xamarin.Android.Support.Design" version="24.2.1"
targetFramework="monoandroid70" />
<package id="Xamarin.Android.Support.Fragment" version="24.2.1"
targetFramework="monoandroid70" />
<package id="Xamarin.Android.Support.Media.Compat" version="24.2.1"
targetFramework="monoandroid70" />
<package id="Xamarin.Android.Support.v4" version="24.2.1"
targetFramework="monoandroid70" />
<package id="Xamarin.Android.Support.v7.AppCompat" version="24.2.1"
targetFramework="monoandroid70" />
<package id="Xamarin.Android.Support.v7.RecyclerView" version="24.2.1"
targetFramework="monoandroid70" />
<package id="Xamarin.Android.Support.Vector.Drawable" version="24.2.1"
targetFramework="monoandroid70" />

**Comment by lbulegato** [comment] 2017-01-26 10:50
Here the stacktrace from Google Play store

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	... 1 more
Caused by: android.runtime.JavaProxyThrowable: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Android.Graphics.RectF'.
  at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00030] in <b72830eae84a465dba3c71c416533d20>:0 
  at Java.Interop.JniPeerMembers+JniInstanceFields.SetValue (System.String encodedMember, Java.Interop.IJavaPeerable self, System.Single value) [0x00001] in <b72830eae84a465dba3c71c416533d20>:0 
  at Android.Graphics.RectF.set_Left (System.Single value) [0x0000a] in <fc5b043c2b92453a93388ea815daa6f7>:0 
  at SignaturePad.SignaturePadView.resetBounds (System.Single touchX, System.Single touchY) [0x0000c] in <2906e1341ea84a8aa79237e119342274>:0 
  at SignaturePad.SignaturePadView.handleTouch (Android.Views.MotionEvent e) [0x00017] in <2906e1341ea84a8aa79237e119342274>:0 
  at SignaturePad.SignaturePadView.OnTouchEvent (Android.Views.MotionEvent e) [0x00080] in <2906e1341ea84a8aa79237e119342274>:0 
  at Android.Views.View.n_OnTouchEvent_Landroid_view_MotionEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_e) [0x00011] in <fc5b043c2b92453a93388ea815daa6f7>:0 
  at (wrapper dynamic-method) System.Object:6a29000a-412b-46d4-9ff4-761cdc08a4b7 (intptr,intptr,intptr)
	at md51e1d049f7f537b278afac351a7caefbb.SignaturePadView.n_onTouchEvent(Native Method)
	at md51e1d049f7f537b278afac351a7caefbb.SignaturePadView.onTouchEvent(SignaturePadView.java:54)
	at android.view.View.dispatchTouchEvent(View.java:9993)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2499)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2831)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1863)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3046)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2792)
	at android.view.View.dispatchPointerEvent(View.java:10228)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5344)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5180)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4673)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4639)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4781)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4647)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4838)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4673)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4639)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4647)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7306)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7184)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7145)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7416)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7380)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7443)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
	at android.view.Choreographer.doCallbacks(Choreographer.java:695)
	at android.view.Choreographer.doFrame(Choreographer.java:625)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	... 3 more
```

**Comment by kalzon1** [comment] 2017-02-01 16:17
I too have this error reported to me from time to time via Google errors.  Most of the time it works fine, but sometimes I get this error reported and the user says they get "kicked out." I'm not sure if that means of the app or just this screen.

I hope this can help to find the issue. Thanks.

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	... 1 more
Caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
  at FieldServiceTrakkerAndroid.InvoiceFinishSignatureActivity.OnCreate (Android.OS.Bundle bundle) [0x00129] in <4a943be01472456ba7e0f6354a44d39f>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <1ad91565e9584a80bbbbdc0b611ea1cd>:0 
  at (wrapper dynamic-method) System.Object:02793528-4c87-45f9-a936-cec5cda975a2 (intptr,intptr,intptr)
	at md53341deb83afdc20fa11e7d16b8b022ec.InvoiceFinishSignatureActivity.n_onCreate(Native Method)
	at md53341deb83afdc20fa11e7d16b8b022ec.InvoiceFinishSignatureActivity.onCreate(InvoiceFinishSignatureActivity.java:30)
	at android.app.Activity.performCreate(Activity.java:6904)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
	at android.app.ActivityThread.access$1100(ActivityThread.java:229)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7325)
	... 3 more

**Comment by lbulegato** [comment] 2017-02-01 16:48
hi @kalzon1  are you able to replicate the error ? I tried multiple times but no way to get this error, I can only see it through crash reports.

**Comment by kalzon1** [comment] 2017-02-01 17:46
Same here.  I only see it in crash reports.  I have not even been able to duplicate it on the various actual devices I run the app on.  I only get it in crash reports from users out in the wild.  

I see it from Android 5.1 and 6.0.  Not yet on 7, but according to google I have almost all of my users on.  (so much harder to fix when you can not duplicate it).

**Comment by kalzon1** [comment] 2017-02-07 00:40
Good News!!!

I've been able to repeatedly duplicate the issue.  It doesn't happen every time, but it did happen many times.

1. Open the signature screen
2. Types in the field where I have it set to type in the signed name
3. Then I can either
   A wait for the device to turn off after x minutes
  B  or just hit the power button so it shuts off
4. leave it off for about 10 seconds
5. I turn the device back on
6. swipe to open the screen
7. Try to start signing my name
8. it immediately gives an error.

Seems to only happen if when I turn the unit back on the Signature field is the 1st one I use.  Seems to be OK, if I go to another field and type and then go to the signature field.

**Comment by lbulegato** [comment] 2017-02-07 09:22
Great Job !! I was able to replicate the bug following your instructions.
I also did a quick and dirty fix that work, simply intercept the disposed exeception and recreate the dirtyrect.

	```
public override bool OnTouchEvent (MotionEvent e)
		{
			float touchX = e.GetX ();
			float touchY = e.GetY ();

			try
			{
				var tmp = dirtyRect.Bottom;
			}
			catch (ObjectDisposedException ex)
			{
				dirtyRect = new RectF();
			}
```

**Comment by kalzon1** [comment] 2017-02-08 20:25
Thanks,
I downloaded the code added your change and so far it's been working fine.

How do we go about getting this change implemented into the  GitHub release from Xamarin?

**Comment by mattleibow** [comment] 2017-03-30 00:13
This should be released in v1.4.1.

**Closed by mattleibow** 2017-03-30 00:13 UTC

**Comment by divyesh008** [comment] 2019-11-22 10:10
@mattleibow I'm facing this issue still in Android.

While i'm running the app in android it throw ObjectDisposedException with this message:

> Cannot access a disposed object.
> Object name: 'Xamarin.Controls.SignaturePadCanvasView'.
>

**Comment by bsohi** [comment] 2020-02-09 21:37
i am seeing this issue in version 3.0.
Cannot access a disposed object.
Object name: 'Xamarin.Controls.SignaturePadCanvasView'.

**Steps to produce**
- scribble signature on signature pad
- navigate to other page
- navigates back to the page where signature control is
- signature control is empty and when I sign it crashes with above exception.
(there is no error if we clear the control first)

**Event method where error occurred**
async void SignaturePad_StrokeCompleted(object sender, System.EventArgs e)
        {
            **var signedImageStream = await SignaturePad.GetImageStreamAsync(SignatureImageFormat.Png);**

            var memoryStream = new System.IO.MemoryStream();
            signedImageStream.CopyTo(memoryStream);
            byte[] bytes = memoryStream.ToArray();

           var fileContentBase64String = System.Convert.ToBase64String(bytes);
        }

Please advise. 
Thx
Balwinder
